name: CI/CD

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
           branch: gh-pages
           folder: ./pages
           github_token: ${{ secrets.GITHUB_TOKEN }}
           target_branch: gh-pages
